### ISSUE TITLE
[Feature Request] Picture-in-Picture

### ISSUE THREAD

**Issue by ayaaop** [hoangvu12/kaguya-app#13]
# Summary:

## Steps to reproduce:
*N/A*
## Expected behavior:
*N/A*
## Additional notes:
*N/A*

**Comment by hoangvu12** [comment]
Right now `react-native-video` doesn't support PIP in Android. Will add when they support it in the future.

https://react-native-video.github.io/react-native-video/component/props#pictureinpicture
