### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by SpaghettDev** [hoangvu12/kaguya-app#54]
I know this isn't the right place to ask this, but I would really appreciate it if you made the chrome extension open-source.
It seems like it already was at one point ([kaguya-extension by Sreekrishna2001](https://github.com/Sreekrishna2001/kaguya-extension)), but the last commit was well over a year ago.

I am asking this since I'm trying to port it to Firefox. Well, I kinda already [have done it](https://github.com/SpaghettDev/kaguya-extension-firefox), but it relies on the minified and obfuscated mess from the Chrome extension store.

So yeah, I would really appreciate it if you updated the source code :)
(Sorry for making an issue here, I couldn't really find a place where it would fit...)

**Comment by hoangvu12** [comment]
The Chrome extension used to be open-sourced but was taken down due to a DMCA. Also, feel free to ask this in the Discord server instead.

**Comment by SpaghettDev** [comment]
> The Chrome extension used to be open-sourced but was taken down due to a DMCA. Also, feel free to ask this in the Discord server instead.

Oh I see, well that's a shame.
I'll join the discord server. Thanks once again.
